version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Apps.Dockerfile
      target: feedback-server-app
    ports:
      - "3001:3001"
    environment:
      DB_CONNECTION: postgresdb
      DB_USER: feedback_user
      DB_PASSWORD: feedback_pass
      DB_PORT: 5432
      DB_DATABASE: feedback_widget
      SERVER_SECRET: superSecureSecret
      SERVER_ALLOWED_ORIGINS: http://localhost:3000
      NODE_ENV: production
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: feedback_user
      POSTGRES_PASSWORD: feedback_pass
      POSTGRES_DB: feedback_widget
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dwn-server:
    container_name: dwn-server
    image: ghcr.io/tbd54566975/dwn-server:dwn-sdk-0.2.4
    ports:
      - "3000:3000"

volumes:
  postgres_data: