apiVersion: database.tbddev.org/v1alpha1
kind: ServerlessPSQL
metadata:
  name: developer-tbd-website-psql-cluster
spec:
  parameters:
    masterUserPasswordSecretRef:
      key: password
      name: developer-tbd-website-psql-master-secret
      namespace: {{ .Release.Namespace }}
    writeConnectionSecretToRef:
      name: developer-tbd-website-psql-secret
      namespace: {{ .Release.Namespace }}
