apiVersion: v1
kind: Secret
metadata:
  name: developer-tbd-website-feedback-app-secret
type: Opaque
stringData:
  SERVER_SECRET: {{ .Values.serverSecret }}
  SERVER_ALLOWED_ORIGINS: {{ .Values.allowedOrigins }}
