import type {
  SidebarsConfig,
  PropSidebarItemLink,
} from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    {
      type: "doc",
      id: "index",
      customProps: { sidebarHeader: "Docs" },
    },
    {
      type: "category",
      label: "SDKs",
      collapsible: false,
      collapsed: false,
      customProps: {
        sidebarHeader: "Docs",
      },
      items: [
        {
          type: "link",
          label: "Web5 SDK",
          href: "web5-sdk",
          className: "web5-icon",
        },
        {
          type: "link",
          label: "tbDex SDK",
          href: "tbdex-sdk",
          className: "tbdex-icon",
        },
      ],
    },
  ],
  web5Sidebar: [
    {
      type: "doc",
      id: "web5-sdk/index",
      customProps: { sidebarHeader: "Web5 SDK" },
    },
    {
      type: "html",
      value: "components",
      customProps: { sidebarHeader: "Web5 SDK" },
    },
    {
      type: "autogenerated",
      dirName: "web5-sdk/dids",
      customProps: { sidebarHeader: "test" },
    },
    // {
    //   type: "link",
    //   label: "Web5 SDK",
    //   href: "learn",
    //   customProps: {
    //     sidebarHeader: "Web5 SDK",
    //   },
    // },
  ],
  tbdexSidebar: {
    "tbDex SDKs": ["tbdex-sdk/index"],
  },
  learnSidebar: [
    {
      type: "category",
      label: "DIDs",
      items: [{ type: "autogenerated", dirName: "web5-sdk/Learn" }],
      customProps: {
        sidebarHeader: "Learn",
      },
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
