/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apiSidebar: [
    {
      type: 'category',
      label: 'APIs',
      link: {
        type: 'doc',
        id: 'index',
      },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
};

module.exports = sidebars;
