module.exports = {
  ColorBlack: '#000000',
  ColorYellow: '#ffec19',
  ColorBlue: '#24f2ff',
  ColorPurple: '#9a1aff',
  ColorWhite: '#ffffff',
  ColorRed: '#ff2e00',
  ColorGreyDark: '#333333',
  GridDesktop: {
    pattern: 'columns',
    gutterSize: 32,
    alignment: 'stretch',
    count: 12,
    offset: 160,
  },
  GridMobile: {
    pattern: 'columns',
    gutterSize: 20,
    alignment: 'stretch',
    count: 4,
    offset: 24,
  },
  GridTablet: {
    pattern: 'columns',
    gutterSize: 20,
    alignment: 'stretch',
    count: 12,
    offset: 34,
  },
  GridStyleGuide: {
    pattern: 'columns',
    gutterSize: 24,
    alignment: 'stretch',
    count: 12,
    offset: 180,
  },
  FontH1D: {
    fontSize: 56,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 700,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: -1,
    lineHeight: 58,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontH2D: {
    fontSize: 24,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 700,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 28,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'uppercase',
  },
  FontBody1D: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 26,
    paragraphIndent: 0,
    paragraphSpacing: 16,
    textCase: 'none',
  },
  FontBody2D: {
    fontSize: 14,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontLinksD: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontInputFieldLabelD: {
    fontSize: 12,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 12,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontTagsD: {
    fontSize: 12,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 12,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontH1M: {
    fontSize: 32,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 700,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: -1,
    lineHeight: 38,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontH2M: {
    fontSize: 24,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 700,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 28,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'uppercase',
  },
  FontBody1M: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 26,
    paragraphIndent: 0,
    paragraphSpacing: 16,
    textCase: 'none',
  },
  FontBody2M: {
    fontSize: 12,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 16,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontLinksM: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 18,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontInputFieldLabelM: {
    fontSize: 12,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 12,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontTagsM: {
    fontSize: 12,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 12,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontH3M: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontH3D: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontH4D: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 700,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 26,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontH4M: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 700,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 26,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontBody1DBold: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 700,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 26,
    paragraphIndent: 0,
    paragraphSpacing: 16,
    textCase: 'none',
  },
  FontBody1MBold: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 700,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 26,
    paragraphIndent: 0,
    paragraphSpacing: 16,
    textCase: 'none',
  },
  FontListItemBulletsD: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 26,
    paragraphIndent: 0,
    paragraphSpacing: 16,
    textCase: 'none',
  },
  FontListItemBulletsM: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 16,
    textCase: 'none',
  },
  FontLinksDUnderline: {
    fontSize: 18,
    textDecoration: 'underline',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 26,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontLinksMUnderline: {
    fontSize: 18,
    textDecoration: 'underline',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 26,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontListItemD: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 26,
    paragraphIndent: 0,
    paragraphSpacing: 16,
    textCase: 'none',
  },
  FontListItemM: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 26,
    paragraphIndent: 0,
    paragraphSpacing: 16,
    textCase: 'none',
  },
  FontTableHeadersD: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 700,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 28,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'uppercase',
  },
  FontTableHeadersM: {
    fontSize: 18,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 700,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 28,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'uppercase',
  },
  FontH2DMedium: {
    fontSize: 24,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 32,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontH2MMedium: {
    fontSize: 24,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 32,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontTagsDUnderline: {
    fontSize: 12,
    textDecoration: 'underline',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 12,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontTagsMUnderline: {
    fontSize: 12,
    textDecoration: 'underline',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 12,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontH3DUnderline: {
    fontSize: 18,
    textDecoration: 'underline',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontH3MUnderline: {
    fontSize: 18,
    textDecoration: 'underline',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 500,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontBody3M: {
    fontSize: 14,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontH1T: {
    fontSize: 48,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 700,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: -1,
    lineHeight: 50,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontBreadcrumbsDUnderline: {
    fontSize: 16,
    textDecoration: 'underline',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  FontBreadcrumbsD: {
    fontSize: 16,
    textDecoration: 'none',
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: 0,
    lineHeight: 20,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  TypographyH1DFontSize: 56,
  TypographyH1DTextDecoration: 'none',
  TypographyH1DFontFamily: 'IBM Plex Mono',
  TypographyH1DFontWeight: 700,
  TypographyH1DFontStyle: 'normal',
  TypographyH1DFontStretch: 'normal',
  TypographyH1DLetterSpacing: -1,
  TypographyH1DLineHeight: 58,
  TypographyH1DParagraphIndent: 0,
  TypographyH1DParagraphSpacing: 0,
  TypographyH1DTextCase: 'none',
  TypographyH2DFontSize: 24,
  TypographyH2DTextDecoration: 'none',
  TypographyH2DFontFamily: 'IBM Plex Mono',
  TypographyH2DFontWeight: 700,
  TypographyH2DFontStyle: 'normal',
  TypographyH2DFontStretch: 'normal',
  TypographyH2DLetterSpacing: 0,
  TypographyH2DLineHeight: 28,
  TypographyH2DParagraphIndent: 0,
  TypographyH2DParagraphSpacing: 0,
  TypographyH2DTextCase: 'uppercase',
  TypographyBody1DFontSize: 18,
  TypographyBody1DTextDecoration: 'none',
  TypographyBody1DFontFamily: 'IBM Plex Mono',
  TypographyBody1DFontWeight: 400,
  TypographyBody1DFontStyle: 'normal',
  TypographyBody1DFontStretch: 'normal',
  TypographyBody1DLetterSpacing: 0,
  TypographyBody1DLineHeight: 26,
  TypographyBody1DParagraphIndent: 0,
  TypographyBody1DParagraphSpacing: 16,
  TypographyBody1DTextCase: 'none',
  TypographyBody2DFontSize: 14,
  TypographyBody2DTextDecoration: 'none',
  TypographyBody2DFontFamily: 'IBM Plex Mono',
  TypographyBody2DFontWeight: 400,
  TypographyBody2DFontStyle: 'normal',
  TypographyBody2DFontStretch: 'normal',
  TypographyBody2DLetterSpacing: 0,
  TypographyBody2DLineHeight: 20,
  TypographyBody2DParagraphIndent: 0,
  TypographyBody2DParagraphSpacing: 0,
  TypographyBody2DTextCase: 'none',
  TypographyLinksDFontSize: 18,
  TypographyLinksDTextDecoration: 'none',
  TypographyLinksDFontFamily: 'IBM Plex Mono',
  TypographyLinksDFontWeight: 500,
  TypographyLinksDFontStyle: 'normal',
  TypographyLinksDFontStretch: 'normal',
  TypographyLinksDLetterSpacing: 0,
  TypographyLinksDLineHeight: 24,
  TypographyLinksDParagraphIndent: 0,
  TypographyLinksDParagraphSpacing: 0,
  TypographyLinksDTextCase: 'none',
  TypographyInputFieldLabelDFontSize: 12,
  TypographyInputFieldLabelDTextDecoration: 'none',
  TypographyInputFieldLabelDFontFamily: 'IBM Plex Mono',
  TypographyInputFieldLabelDFontWeight: 400,
  TypographyInputFieldLabelDFontStyle: 'normal',
  TypographyInputFieldLabelDFontStretch: 'normal',
  TypographyInputFieldLabelDLetterSpacing: 0,
  TypographyInputFieldLabelDLineHeight: 12,
  TypographyInputFieldLabelDParagraphIndent: 0,
  TypographyInputFieldLabelDParagraphSpacing: 0,
  TypographyInputFieldLabelDTextCase: 'none',
  TypographyTagsDFontSize: 12,
  TypographyTagsDTextDecoration: 'none',
  TypographyTagsDFontFamily: 'IBM Plex Mono',
  TypographyTagsDFontWeight: 500,
  TypographyTagsDFontStyle: 'normal',
  TypographyTagsDFontStretch: 'normal',
  TypographyTagsDLetterSpacing: 0,
  TypographyTagsDLineHeight: 12,
  TypographyTagsDParagraphIndent: 0,
  TypographyTagsDParagraphSpacing: 0,
  TypographyTagsDTextCase: 'none',
  TypographyH1MFontSize: 32,
  TypographyH1MTextDecoration: 'none',
  TypographyH1MFontFamily: 'IBM Plex Mono',
  TypographyH1MFontWeight: 700,
  TypographyH1MFontStyle: 'normal',
  TypographyH1MFontStretch: 'normal',
  TypographyH1MLetterSpacing: -1,
  TypographyH1MLineHeight: 38,
  TypographyH1MParagraphIndent: 0,
  TypographyH1MParagraphSpacing: 0,
  TypographyH1MTextCase: 'none',
  TypographyH2MFontSize: 24,
  TypographyH2MTextDecoration: 'none',
  TypographyH2MFontFamily: 'IBM Plex Mono',
  TypographyH2MFontWeight: 700,
  TypographyH2MFontStyle: 'normal',
  TypographyH2MFontStretch: 'normal',
  TypographyH2MLetterSpacing: 0,
  TypographyH2MLineHeight: 28,
  TypographyH2MParagraphIndent: 0,
  TypographyH2MParagraphSpacing: 0,
  TypographyH2MTextCase: 'uppercase',
  TypographyBody1MFontSize: 18,
  TypographyBody1MTextDecoration: 'none',
  TypographyBody1MFontFamily: 'IBM Plex Mono',
  TypographyBody1MFontWeight: 400,
  TypographyBody1MFontStyle: 'normal',
  TypographyBody1MFontStretch: 'normal',
  TypographyBody1MLetterSpacing: 0,
  TypographyBody1MLineHeight: 26,
  TypographyBody1MParagraphIndent: 0,
  TypographyBody1MParagraphSpacing: 16,
  TypographyBody1MTextCase: 'none',
  TypographyBody2MFontSize: 12,
  TypographyBody2MTextDecoration: 'none',
  TypographyBody2MFontFamily: 'IBM Plex Mono',
  TypographyBody2MFontWeight: 400,
  TypographyBody2MFontStyle: 'normal',
  TypographyBody2MFontStretch: 'normal',
  TypographyBody2MLetterSpacing: 0,
  TypographyBody2MLineHeight: 16,
  TypographyBody2MParagraphIndent: 0,
  TypographyBody2MParagraphSpacing: 0,
  TypographyBody2MTextCase: 'none',
  TypographyLinksMFontSize: 18,
  TypographyLinksMTextDecoration: 'none',
  TypographyLinksMFontFamily: 'IBM Plex Mono',
  TypographyLinksMFontWeight: 500,
  TypographyLinksMFontStyle: 'normal',
  TypographyLinksMFontStretch: 'normal',
  TypographyLinksMLetterSpacing: 0,
  TypographyLinksMLineHeight: 18,
  TypographyLinksMParagraphIndent: 0,
  TypographyLinksMParagraphSpacing: 0,
  TypographyLinksMTextCase: 'none',
  TypographyInputFieldLabelMFontSize: 12,
  TypographyInputFieldLabelMTextDecoration: 'none',
  TypographyInputFieldLabelMFontFamily: 'IBM Plex Mono',
  TypographyInputFieldLabelMFontWeight: 400,
  TypographyInputFieldLabelMFontStyle: 'normal',
  TypographyInputFieldLabelMFontStretch: 'normal',
  TypographyInputFieldLabelMLetterSpacing: 0,
  TypographyInputFieldLabelMLineHeight: 12,
  TypographyInputFieldLabelMParagraphIndent: 0,
  TypographyInputFieldLabelMParagraphSpacing: 0,
  TypographyInputFieldLabelMTextCase: 'none',
  TypographyTagsMFontSize: 12,
  TypographyTagsMTextDecoration: 'none',
  TypographyTagsMFontFamily: 'IBM Plex Mono',
  TypographyTagsMFontWeight: 500,
  TypographyTagsMFontStyle: 'normal',
  TypographyTagsMFontStretch: 'normal',
  TypographyTagsMLetterSpacing: 0,
  TypographyTagsMLineHeight: 12,
  TypographyTagsMParagraphIndent: 0,
  TypographyTagsMParagraphSpacing: 0,
  TypographyTagsMTextCase: 'none',
  TypographyH3MFontSize: 18,
  TypographyH3MTextDecoration: 'none',
  TypographyH3MFontFamily: 'IBM Plex Mono',
  TypographyH3MFontWeight: 500,
  TypographyH3MFontStyle: 'normal',
  TypographyH3MFontStretch: 'normal',
  TypographyH3MLetterSpacing: 0,
  TypographyH3MLineHeight: 24,
  TypographyH3MParagraphIndent: 0,
  TypographyH3MParagraphSpacing: 0,
  TypographyH3MTextCase: 'none',
  TypographyH3DFontSize: 18,
  TypographyH3DTextDecoration: 'none',
  TypographyH3DFontFamily: 'IBM Plex Mono',
  TypographyH3DFontWeight: 500,
  TypographyH3DFontStyle: 'normal',
  TypographyH3DFontStretch: 'normal',
  TypographyH3DLetterSpacing: 0,
  TypographyH3DLineHeight: 24,
  TypographyH3DParagraphIndent: 0,
  TypographyH3DParagraphSpacing: 0,
  TypographyH3DTextCase: 'none',
  TypographyH4DFontSize: 18,
  TypographyH4DTextDecoration: 'none',
  TypographyH4DFontFamily: 'IBM Plex Mono',
  TypographyH4DFontWeight: 700,
  TypographyH4DFontStyle: 'normal',
  TypographyH4DFontStretch: 'normal',
  TypographyH4DLetterSpacing: 0,
  TypographyH4DLineHeight: 26,
  TypographyH4DParagraphIndent: 0,
  TypographyH4DParagraphSpacing: 0,
  TypographyH4DTextCase: 'none',
  TypographyH4MFontSize: 18,
  TypographyH4MTextDecoration: 'none',
  TypographyH4MFontFamily: 'IBM Plex Mono',
  TypographyH4MFontWeight: 700,
  TypographyH4MFontStyle: 'normal',
  TypographyH4MFontStretch: 'normal',
  TypographyH4MLetterSpacing: 0,
  TypographyH4MLineHeight: 26,
  TypographyH4MParagraphIndent: 0,
  TypographyH4MParagraphSpacing: 0,
  TypographyH4MTextCase: 'none',
  TypographyBody1DBoldFontSize: 18,
  TypographyBody1DBoldTextDecoration: 'none',
  TypographyBody1DBoldFontFamily: 'IBM Plex Mono',
  TypographyBody1DBoldFontWeight: 700,
  TypographyBody1DBoldFontStyle: 'normal',
  TypographyBody1DBoldFontStretch: 'normal',
  TypographyBody1DBoldLetterSpacing: 0,
  TypographyBody1DBoldLineHeight: 26,
  TypographyBody1DBoldParagraphIndent: 0,
  TypographyBody1DBoldParagraphSpacing: 16,
  TypographyBody1DBoldTextCase: 'none',
  TypographyBody1MBoldFontSize: 18,
  TypographyBody1MBoldTextDecoration: 'none',
  TypographyBody1MBoldFontFamily: 'IBM Plex Mono',
  TypographyBody1MBoldFontWeight: 700,
  TypographyBody1MBoldFontStyle: 'normal',
  TypographyBody1MBoldFontStretch: 'normal',
  TypographyBody1MBoldLetterSpacing: 0,
  TypographyBody1MBoldLineHeight: 26,
  TypographyBody1MBoldParagraphIndent: 0,
  TypographyBody1MBoldParagraphSpacing: 16,
  TypographyBody1MBoldTextCase: 'none',
  TypographyListItemBulletsDFontSize: 18,
  TypographyListItemBulletsDTextDecoration: 'none',
  TypographyListItemBulletsDFontFamily: 'IBM Plex Mono',
  TypographyListItemBulletsDFontWeight: 400,
  TypographyListItemBulletsDFontStyle: 'normal',
  TypographyListItemBulletsDFontStretch: 'normal',
  TypographyListItemBulletsDLetterSpacing: 0,
  TypographyListItemBulletsDLineHeight: 26,
  TypographyListItemBulletsDParagraphIndent: 0,
  TypographyListItemBulletsDParagraphSpacing: 16,
  TypographyListItemBulletsDTextCase: 'none',
  TypographyListItemBulletsMFontSize: 18,
  TypographyListItemBulletsMTextDecoration: 'none',
  TypographyListItemBulletsMFontFamily: 'IBM Plex Mono',
  TypographyListItemBulletsMFontWeight: 400,
  TypographyListItemBulletsMFontStyle: 'normal',
  TypographyListItemBulletsMFontStretch: 'normal',
  TypographyListItemBulletsMLetterSpacing: 0,
  TypographyListItemBulletsMLineHeight: 24,
  TypographyListItemBulletsMParagraphIndent: 0,
  TypographyListItemBulletsMParagraphSpacing: 16,
  TypographyListItemBulletsMTextCase: 'none',
  TypographyLinksDUnderlineFontSize: 18,
  TypographyLinksDUnderlineTextDecoration: 'underline',
  TypographyLinksDUnderlineFontFamily: 'IBM Plex Mono',
  TypographyLinksDUnderlineFontWeight: 500,
  TypographyLinksDUnderlineFontStyle: 'normal',
  TypographyLinksDUnderlineFontStretch: 'normal',
  TypographyLinksDUnderlineLetterSpacing: 0,
  TypographyLinksDUnderlineLineHeight: 26,
  TypographyLinksDUnderlineParagraphIndent: 0,
  TypographyLinksDUnderlineParagraphSpacing: 0,
  TypographyLinksDUnderlineTextCase: 'none',
  TypographyLinksMUnderlineFontSize: 18,
  TypographyLinksMUnderlineTextDecoration: 'underline',
  TypographyLinksMUnderlineFontFamily: 'IBM Plex Mono',
  TypographyLinksMUnderlineFontWeight: 500,
  TypographyLinksMUnderlineFontStyle: 'normal',
  TypographyLinksMUnderlineFontStretch: 'normal',
  TypographyLinksMUnderlineLetterSpacing: 0,
  TypographyLinksMUnderlineLineHeight: 26,
  TypographyLinksMUnderlineParagraphIndent: 0,
  TypographyLinksMUnderlineParagraphSpacing: 0,
  TypographyLinksMUnderlineTextCase: 'none',
  TypographyListItemDFontSize: 18,
  TypographyListItemDTextDecoration: 'none',
  TypographyListItemDFontFamily: 'IBM Plex Mono',
  TypographyListItemDFontWeight: 500,
  TypographyListItemDFontStyle: 'normal',
  TypographyListItemDFontStretch: 'normal',
  TypographyListItemDLetterSpacing: 0,
  TypographyListItemDLineHeight: 26,
  TypographyListItemDParagraphIndent: 0,
  TypographyListItemDParagraphSpacing: 16,
  TypographyListItemDTextCase: 'none',
  TypographyListItemMFontSize: 18,
  TypographyListItemMTextDecoration: 'none',
  TypographyListItemMFontFamily: 'IBM Plex Mono',
  TypographyListItemMFontWeight: 500,
  TypographyListItemMFontStyle: 'normal',
  TypographyListItemMFontStretch: 'normal',
  TypographyListItemMLetterSpacing: 0,
  TypographyListItemMLineHeight: 26,
  TypographyListItemMParagraphIndent: 0,
  TypographyListItemMParagraphSpacing: 16,
  TypographyListItemMTextCase: 'none',
  TypographyTableHeadersDFontSize: 18,
  TypographyTableHeadersDTextDecoration: 'none',
  TypographyTableHeadersDFontFamily: 'IBM Plex Mono',
  TypographyTableHeadersDFontWeight: 700,
  TypographyTableHeadersDFontStyle: 'normal',
  TypographyTableHeadersDFontStretch: 'normal',
  TypographyTableHeadersDLetterSpacing: 0,
  TypographyTableHeadersDLineHeight: 28,
  TypographyTableHeadersDParagraphIndent: 0,
  TypographyTableHeadersDParagraphSpacing: 0,
  TypographyTableHeadersDTextCase: 'uppercase',
  TypographyTableHeadersMFontSize: 18,
  TypographyTableHeadersMTextDecoration: 'none',
  TypographyTableHeadersMFontFamily: 'IBM Plex Mono',
  TypographyTableHeadersMFontWeight: 700,
  TypographyTableHeadersMFontStyle: 'normal',
  TypographyTableHeadersMFontStretch: 'normal',
  TypographyTableHeadersMLetterSpacing: 0,
  TypographyTableHeadersMLineHeight: 28,
  TypographyTableHeadersMParagraphIndent: 0,
  TypographyTableHeadersMParagraphSpacing: 0,
  TypographyTableHeadersMTextCase: 'uppercase',
  TypographyH2DMediumFontSize: 24,
  TypographyH2DMediumTextDecoration: 'none',
  TypographyH2DMediumFontFamily: 'IBM Plex Mono',
  TypographyH2DMediumFontWeight: 500,
  TypographyH2DMediumFontStyle: 'normal',
  TypographyH2DMediumFontStretch: 'normal',
  TypographyH2DMediumLetterSpacing: 0,
  TypographyH2DMediumLineHeight: 32,
  TypographyH2DMediumParagraphIndent: 0,
  TypographyH2DMediumParagraphSpacing: 0,
  TypographyH2DMediumTextCase: 'none',
  TypographyH2MMediumFontSize: 24,
  TypographyH2MMediumTextDecoration: 'none',
  TypographyH2MMediumFontFamily: 'IBM Plex Mono',
  TypographyH2MMediumFontWeight: 500,
  TypographyH2MMediumFontStyle: 'normal',
  TypographyH2MMediumFontStretch: 'normal',
  TypographyH2MMediumLetterSpacing: 0,
  TypographyH2MMediumLineHeight: 32,
  TypographyH2MMediumParagraphIndent: 0,
  TypographyH2MMediumParagraphSpacing: 0,
  TypographyH2MMediumTextCase: 'none',
  TypographyTagsDUnderlineFontSize: 12,
  TypographyTagsDUnderlineTextDecoration: 'underline',
  TypographyTagsDUnderlineFontFamily: 'IBM Plex Mono',
  TypographyTagsDUnderlineFontWeight: 500,
  TypographyTagsDUnderlineFontStyle: 'normal',
  TypographyTagsDUnderlineFontStretch: 'normal',
  TypographyTagsDUnderlineLetterSpacing: 0,
  TypographyTagsDUnderlineLineHeight: 12,
  TypographyTagsDUnderlineParagraphIndent: 0,
  TypographyTagsDUnderlineParagraphSpacing: 0,
  TypographyTagsDUnderlineTextCase: 'none',
  TypographyTagsMUnderlineFontSize: 12,
  TypographyTagsMUnderlineTextDecoration: 'underline',
  TypographyTagsMUnderlineFontFamily: 'IBM Plex Mono',
  TypographyTagsMUnderlineFontWeight: 500,
  TypographyTagsMUnderlineFontStyle: 'normal',
  TypographyTagsMUnderlineFontStretch: 'normal',
  TypographyTagsMUnderlineLetterSpacing: 0,
  TypographyTagsMUnderlineLineHeight: 12,
  TypographyTagsMUnderlineParagraphIndent: 0,
  TypographyTagsMUnderlineParagraphSpacing: 0,
  TypographyTagsMUnderlineTextCase: 'none',
  TypographyH3DUnderlineFontSize: 18,
  TypographyH3DUnderlineTextDecoration: 'underline',
  TypographyH3DUnderlineFontFamily: 'IBM Plex Mono',
  TypographyH3DUnderlineFontWeight: 500,
  TypographyH3DUnderlineFontStyle: 'normal',
  TypographyH3DUnderlineFontStretch: 'normal',
  TypographyH3DUnderlineLetterSpacing: 0,
  TypographyH3DUnderlineLineHeight: 24,
  TypographyH3DUnderlineParagraphIndent: 0,
  TypographyH3DUnderlineParagraphSpacing: 0,
  TypographyH3DUnderlineTextCase: 'none',
  TypographyH3MUnderlineFontSize: 18,
  TypographyH3MUnderlineTextDecoration: 'underline',
  TypographyH3MUnderlineFontFamily: 'IBM Plex Mono',
  TypographyH3MUnderlineFontWeight: 500,
  TypographyH3MUnderlineFontStyle: 'normal',
  TypographyH3MUnderlineFontStretch: 'normal',
  TypographyH3MUnderlineLetterSpacing: 0,
  TypographyH3MUnderlineLineHeight: 24,
  TypographyH3MUnderlineParagraphIndent: 0,
  TypographyH3MUnderlineParagraphSpacing: 0,
  TypographyH3MUnderlineTextCase: 'none',
  TypographyBody3MFontSize: 14,
  TypographyBody3MTextDecoration: 'none',
  TypographyBody3MFontFamily: 'IBM Plex Mono',
  TypographyBody3MFontWeight: 400,
  TypographyBody3MFontStyle: 'normal',
  TypographyBody3MFontStretch: 'normal',
  TypographyBody3MLetterSpacing: 0,
  TypographyBody3MLineHeight: 20,
  TypographyBody3MParagraphIndent: 0,
  TypographyBody3MParagraphSpacing: 0,
  TypographyBody3MTextCase: 'none',
  TypographyH1TFontSize: 48,
  TypographyH1TTextDecoration: 'none',
  TypographyH1TFontFamily: 'IBM Plex Mono',
  TypographyH1TFontWeight: 700,
  TypographyH1TFontStyle: 'normal',
  TypographyH1TFontStretch: 'normal',
  TypographyH1TLetterSpacing: -1,
  TypographyH1TLineHeight: 50,
  TypographyH1TParagraphIndent: 0,
  TypographyH1TParagraphSpacing: 0,
  TypographyH1TTextCase: 'none',
  TypographyBreadcrumbsDUnderlineFontSize: 16,
  TypographyBreadcrumbsDUnderlineTextDecoration: 'underline',
  TypographyBreadcrumbsDUnderlineFontFamily: 'IBM Plex Mono',
  TypographyBreadcrumbsDUnderlineFontWeight: 400,
  TypographyBreadcrumbsDUnderlineFontStyle: 'normal',
  TypographyBreadcrumbsDUnderlineFontStretch: 'normal',
  TypographyBreadcrumbsDUnderlineLetterSpacing: 0,
  TypographyBreadcrumbsDUnderlineLineHeight: 20,
  TypographyBreadcrumbsDUnderlineParagraphIndent: 0,
  TypographyBreadcrumbsDUnderlineParagraphSpacing: 0,
  TypographyBreadcrumbsDUnderlineTextCase: 'none',
  TypographyBreadcrumbsDFontSize: 16,
  TypographyBreadcrumbsDTextDecoration: 'none',
  TypographyBreadcrumbsDFontFamily: 'IBM Plex Mono',
  TypographyBreadcrumbsDFontWeight: 400,
  TypographyBreadcrumbsDFontStyle: 'normal',
  TypographyBreadcrumbsDFontStretch: 'normal',
  TypographyBreadcrumbsDLetterSpacing: 0,
  TypographyBreadcrumbsDLineHeight: 20,
  TypographyBreadcrumbsDParagraphIndent: 0,
  TypographyBreadcrumbsDParagraphSpacing: 0,
  TypographyBreadcrumbsDTextCase: 'none',
};
