// Autogenerated from ALR project creation command "cargo new $projectName --library"
// @see docs https://doc.rust-lang.org/beta/book/ch11-01-writing-tests.html
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
