name: Security and License Scans

on:
  pull_request: #todo: _target:
    branches:
      - main

  push:
    branches:
      - main

  # Run every day at 5am UTC
  schedule:
    - cron: "0 5 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  security-license-scan:
    uses: TBD54566975/open-source-programs/.github/workflows/security.yml@leordev/reusable-workflows
    secrets: inherit
