name: Test and Deploy to Netlify

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Netlify Build via Build Hook
      run: curl -X POST -d {} ${{ secrets.TEST_BUILDHOOK }}
